import os
env = Environment()
current_path = os.getcwd()
test_root=os.path.dirname(current_path)+"/server/"

env.Append(CPPPATH = [current_path, test_root])

env.Append(LIBPATH = [
           ])

env.Append(LIBS = [])


env.Append(CCFLAGS = ['-Wall', '-O2', '-g', '-std=c++11'])


env.Program(
        target="test_tcpsocket",
        source=["test_tcpsocket.cpp",test_root+"/tcpsocket.cpp"]
)
