import os
env = Environment()
current_path = os.getcwd()
http_root=os.path.dirname(current_path)+"/http/"
comm_root=os.path.dirname(current_path)+"/comm/"

env.Append(CPPPATH = [current_path, http_root,comm_root])

env.Append(LIBPATH = [
           ])

env.Append(LIBS = [])


env.Append(CCFLAGS = ['-Wall', '-O2', '-g', '-std=c++11'])


env.Program(
        target="main",
        source=["main.cpp","tcpsocket.cpp",comm_root+"/socket_util.cpp",http_root+"/httpparse.cpp"]
)
